name: dbt_techstore
version: "1.0.0"
config-version: 2

profile: techstore

model-paths: ["models"]
macro-paths: ["macros"]

on-run-start:
  - "{{ create_raw_views() }}"

models:
  dbt_techstore:
    staging:
      +materialized: table
      +schema: staging
    consume:
      +materialized: table
      +schema: consume
