techstore:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', '/app/output/lake.duckdb') }}"
      threads: 4
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', './output/lake.duckdb') }}"
      threads: 4
