version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: clientes
      - name: productos
      - name: pedidos
      - name: detalle_pedidos
      - name: pagos_banco
      - name: envios_courier
      - name: catalogo_proveedor
      - name: liquidacion_mp
      - name: reclamos
      - name: dolar
      - name: feriados
      - name: ecomm_vtex_pedido
      - name: ecomm_meli_pedido
      - name: ecomm_meli_shipping
      - name: ecomm_meli_pickup
      - name: ecomm_garbarino_pedido
