FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline_ecommerce.py .
COPY init.sql .
COPY start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
